//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendingMachine.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get change.
        /// </summary>
        internal static string _en_Change {
            get {
                return ResourceManager.GetString("_en_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AVAILABILITY DRINKS.
        /// </summary>
        internal static string _en_DrinksGroup {
            get {
                return ResourceManager.GetString("_en_DrinksGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} = price: {1} RUR, availability: {2} drink..
        /// </summary>
        internal static string _en_GoodsDescription {
            get {
                return ResourceManager.GetString("_en_GoodsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insufficient funds!.
        /// </summary>
        internal static string _en_InsufficientMessage {
            get {
                return ResourceManager.GetString("_en_InsufficientMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RUR.
        /// </summary>
        internal static string _en_PayCurrency {
            get {
                return ResourceManager.GetString("_en_PayCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PAID.
        /// </summary>
        internal static string _en_PayGroup {
            get {
                return ResourceManager.GetString("_en_PayGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OUTPUT QUEUE.
        /// </summary>
        internal static string _en_Queue {
            get {
                return ResourceManager.GetString("_en_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thanks!.
        /// </summary>
        internal static string _en_ThanksMessage {
            get {
                return ResourceManager.GetString("_en_ThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Взять сдачу.
        /// </summary>
        internal static string _ru_Change {
            get {
                return ResourceManager.GetString("_ru_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАПИТКИ В НАЛИЧИИ.
        /// </summary>
        internal static string _ru_DrinksGroup {
            get {
                return ResourceManager.GetString("_ru_DrinksGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} = цена: {1} руб., наличие: {2} порций..
        /// </summary>
        internal static string _ru_GoodsDescription {
            get {
                return ResourceManager.GetString("_ru_GoodsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно средств!.
        /// </summary>
        internal static string _ru_InsufficientMessage {
            get {
                return ResourceManager.GetString("_ru_InsufficientMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на руб..
        /// </summary>
        internal static string _ru_PayCurrency {
            get {
                return ResourceManager.GetString("_ru_PayCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВНЕСЕНО.
        /// </summary>
        internal static string _ru_PayGroup {
            get {
                return ResourceManager.GetString("_ru_PayGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОЧЕРЕДЬ ВЫДАЧИ.
        /// </summary>
        internal static string _ru_Queue {
            get {
                return ResourceManager.GetString("_ru_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо!.
        /// </summary>
        internal static string _ru_ThanksMessage {
            get {
                return ResourceManager.GetString("_ru_ThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CoffeeCup {
            get {
                object obj = ResourceManager.GetObject("CoffeeCup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CoffeeCup.
        /// </summary>
        internal static string CoffeeImageName {
            get {
                return ResourceManager.GetString("CoffeeImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JuiceGlass {
            get {
                object obj = ResourceManager.GetObject("JuiceGlass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JuiceGlass.
        /// </summary>
        internal static string JuiceImageName {
            get {
                return ResourceManager.GetString("JuiceImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProgressCup {
            get {
                object obj = ResourceManager.GetObject("ProgressCup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProgressCup.
        /// </summary>
        internal static string ProgressImageName {
            get {
                return ResourceManager.GetString("ProgressImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TeapotCup.
        /// </summary>
        internal static string TeaImageName {
            get {
                return ResourceManager.GetString("TeaImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TeapotCup {
            get {
                object obj = ResourceManager.GetObject("TeapotCup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
